# 监控管理
management:
  endpoints:
    web:
      exposure:
        # web暴露端点包含，默认[health]
        include: health
  endpoint:
    health: # 开启health 配置从不展示细节
      probes:
        # 是否启用活体和就绪探测
        enabled: true
      # 何时显示完整的运行状况详细信息
      show-details: never
  health:
    # 存活探针: /actuator/health/liveness
    livenessState:
      enabled: true
    # 就绪探针: /actuator/health/readiness
    readinessState:
      enabled: true

# spring配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1/moyu?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: moyu
    password: cTEL2ctLLCBWxWbt
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # 业务redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

# Sa-Token 配置
sa-token:
  # Token名称
  token-name: Authorization
  # token 提交时的前缀
  token-prefix: Bearer
  # jwt格式的token秘钥，至少256-bit(32-byte)，如：7nPXLm0zLVdqKM5QTb03ahcRiWzoC2UC
  jwt-secret-key: 7nPXLm0zLVdqKM5QTb03ahcRiWzoC2UC
  # Token有效期 3天
  timeout: 259200
  # Token风格
  token-style: uuid

  # 配置 Sa-Token 单独使用的 Redis 连接
  alone-redis:
    # Redis模式(默认单体)
    # pattern: single
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password:
    # 连接超时时间（毫秒）
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

# 自定义配置
custom:
  # 自定义Spring Security配置
  security:
    # 是否启用认证，为false时等同于全加白
    enabled: true
    # 会话配置
    session:
      # 认证策略类型 jwt redis
      type: redis
    # 白名单列表，仅跳过 AuthorizationFilter 过滤器，还是会走其他过滤器(CSRF、CORS等)
    white-list:
      # 认证授权类
      - /api/auth/login/**
      # 回调、远程调用类
      - /callback/**
      - /feign/**
      # 监控管理类
      - /actuator/**
      - /monitor/**

